apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: knowledge-graph
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/knowledge-graph
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-demo-repo
  targetNamespace: default
