apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"worker-svc"},"name":"worker-svc","namespace":"verus-dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"worker-svc"}},"template":{"metadata":{"labels":{"app":"worker-svc","version":"v1"}},"spec":{"containers":[{"env":[{"name":"TEMPORAL_ADDRESS","value":"temporal.default.svc.cluster.local:7233"},{"name":"TEMPORAL_NAMESPACE","value":"default"},{"name":"POSTGRES_SSLMODE","value":"disable"}],"envFrom":[{"secretRef":{"name":"worker-svc-secret"}}],"image":"010438496771.dkr.ecr.us-east-2.amazonaws.com/verus-worker:latest","imagePullPolicy":"Always","name":"worker","resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}],"serviceAccountName":"default"}}}}
  creationTimestamp: "2026-02-18T21:32:07Z"
  generation: 6
  labels:
    app: worker-svc
  name: worker-svc
  namespace: verus-dev
  resourceVersion: "54203351"
  uid: 7bc8f459-6560-4191-980c-51f15cfc676c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: worker-svc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: worker-svc
        version: v1
    spec:
      containers:
      - env:
        - name: TEMPORAL_ADDRESS
          value: temporal-frontend.verus-dev.svc.cluster.local:7233
        - name: TEMPORAL_NAMESPACE
          value: default
        - name: POSTGRES_SSLMODE
          value: disable
        - name: GRPC_PORT
          value: "9090"
        envFrom:
        - secretRef:
            name: worker-svc-secret
        image: 010438496771.dkr.ecr.us-east-2.amazonaws.com/verus-worker:bbc17a7
        imagePullPolicy: Always
        name: worker
        ports:
        - containerPort: 9090
          name: grpc
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-02-18T21:33:33Z"
    lastUpdateTime: "2026-02-18T21:33:33Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-02-18T21:32:08Z"
    lastUpdateTime: "2026-02-19T14:39:00Z"
    message: ReplicaSet "worker-svc-645d4bb7bd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
