apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: verus-frontend
  namespace: flux-system
spec:
  image: 010438496771.dkr.ecr.us-east-2.amazonaws.com/verus-frontend
  interval: 5m
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: verus-frontend-dev
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: verus-frontend
  policy:
    semver:
      range: '>=0.1.0-alpha'
  filterTags:
    pattern: '^(?P<version>.*-alpha\..*)$'
    extract: '$version'
