apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: auth
  namespace: flux-system
spec:
  image: 010438496771.dkr.ecr.us-east-2.amazonaws.com/verus-auth-svc
  interval: 5m
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: auth-dev
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: auth
  policy:
    semver:
      range: '>=0.1.0-alpha'
  filterTags:
    pattern: '^(?P<version>.*-alpha\..*)$'
    extract: '$version'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: auth-stg
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: auth
  policy:
    semver:
      range: '>=1.0.0'
