apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: auth-dev
  namespace: flux-system
spec:
  targetNamespace: verus-dev
  interval: 5m
  chart:
    spec:
      chart: ./services/auth/helm/auth
      sourceRef:
        kind: GitRepository
        name: verus-go-dev
        namespace: flux-system
      interval: 1m
  values:
    environment: dev
    image:
      tag: latest # {"$imagepolicy": "flux-system:auth-dev:tag"}
    serviceAccount:
      create: true
    autoscaling:
      enabled: false
    ingress:
      useSubpath: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: auth-stg
  namespace: flux-system
spec:
  suspend: true
  targetNamespace: verus-stg
  interval: 5m
  chart:
    spec:
      chart: ./services/auth/helm/auth
      sourceRef:
        kind: GitRepository
        name: verus-go-stg
        namespace: flux-system
      interval: 1m
  values:
    environment: stg
    image:
      tag: latest # {"$imagepolicy": "flux-system:auth-stg:tag"}
    serviceAccount:
      create: true
    autoscaling:
      enabled: false
    ingress:
      useSubpath: true
