apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neo4j-dev
  namespace: flux-system
spec:
  suspend: false
  targetNamespace: verus-dev
  interval: 5m
  install:
    disableWait: true
  upgrade:
    disableWait: true
  chart:
    spec:
      chart: ./helm/neo4j
      sourceRef:
        kind: GitRepository
        name: verus-neo4j-dev
        namespace: flux-system
      interval: 1m
  values:
    environment: dev
    app:
      image:
        tag: latest # {"$imagepolicy": "flux-system:neo4j-dev:tag"}
      config:
        NEO4J_URI: "bolt://verus-dev-neo4j-dev:7687"
        NEO4J_USER: "neo4j"
      secrets:
        NEO4J_PASSWORD:
          key: "dev/verus-neo4j"
          property: "NEO4J_PASSWORD"
      ingress:
        enabled: true
        host: verus-dev.districtcyber.io
        path: /com.verus.neo4j.grpc.Neo4jService
    db:
      persistence:
        enabled: true
        size: 10Gi
      auth:
        password: "password"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neo4j-stg
  namespace: flux-system
spec:
  suspend: true
  targetNamespace: verus-stg
  interval: 5m
  chart:
    spec:
      chart: ./helm/neo4j
      sourceRef:
        kind: GitRepository
        name: verus-neo4j-stg
        namespace: flux-system
      interval: 1m
  values:
    environment: stg
    app:
      ingress:
        host: neo4j-stg.districtcyber.io
        path: /
