apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: catalog
  namespace: flux-system
spec:
  image: 010438496771.dkr.ecr.us-east-2.amazonaws.com/verus-catalog-svc
  interval: 1m
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: catalog-dev
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: catalog
  policy:
    semver:
      range: '>=0.1.0-alpha'
  filterTags:
    pattern: '^(?P<version>.*-alpha\..*)$'
    extract: '$version'
